language: go

services:
- redis-server

go:
  - 1.3
  - 1.4

install:
  - go get gopkg.in/bufio.v1
  - go get gopkg.in/bsm/ratelimit.v1
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv $HOME/gopath/src/github.com/go-redis/redis $HOME/gopath/src/gopkg.in/redis.v3
  - cd $HOME/gopath/src/gopkg.in/redis.v3
