language: go

services:
- redis-server

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get gopkg.in/bufio.v1
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv $HOME/gopath/src/github.com/go-redis/redis $HOME/gopath/src/gopkg.in/redis.v2
  - cd $HOME/gopath/src/gopkg.in/redis.v2

before_script:
  - redis-server testdata/sentinel.conf --sentinel &
