# See https://prometheus.io/docs/alerting/latest/configuration/ for details.

global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: false

receivers:
  - name: 'team-X'
    email_configs:
      - to: 'some-receiver@example.com'
        send_resolved: true

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname', 'cluster', 'service']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h

  # A default receiver
  receiver: team-X

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

  # The child route trees.
  routes:
    # This route matches error alerts created from spans or logs.
    - matchers:
        - alert_kind="error"
      group_interval: 24h
      receiver: team-X

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/template/*.tmpl'
